# @Author: German Cano Quiveu <germancq>
# @Date:   2019-03-04T13:50:55+01:00
# @Email:  germancq@dte.us.es
# @Last modified by:   germancq
# @Last modified time: 2019-03-04T13:53:18+01:00

VERILOG_SOURCES = ../../../rtl/verilog/7_seg/div_clk_module.v \
									../../../rtl/verilog/misc/contador_up.v
TOPLEVEL=div_clk_module
MODULE=div_clk_module_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
