# @Author: German Cano Quiveu <germancq>
# @Date:   2019-03-01T15:51:46+01:00
# @Email:  germancq@dte.us.es
# @Filename: Makefile
# @Last modified by:   germancq
# @Last modified time: 2019-03-01T16:29:27+01:00

VERILOG_SOURCES = ../../../rtl/verilog/7_seg/dec_to_7_seg.v
TOPLEVEL=dec_to_7_seg
MODULE=dec_to_7_seg_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
