# @Author: German Cano Quiveu <germancq>
# @Date:   2019-03-01T17:02:58+01:00
# @Email:  germancq@dte.us.es
# @Filename: Makefile
# @Last modified by:   germancq
# @Last modified time: 2019-03-01T17:10:19+01:00

VERILOG_SOURCES = ../../../rtl/verilog/7_seg/mux_8.v \
									../../../rtl/verilog/misc/genericMux.v
TOPLEVEL=mux_8
MODULE=mux_8_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
