# @Author: German Cano Quiveu <germancq>
# @Date:   2019-03-01T17:13:29+01:00
# @Email:  germancq@dte.us.es
# @Filename: Makefile
# @Last modified by:   germancq
# @Last modified time: 2019-03-01T17:14:04+01:00

VERILOG_SOURCES = ../../../rtl/verilog/7_seg/an_gen.v
TOPLEVEL=an_gen
MODULE=an_gen_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
